importScripts("core.js","advanced.js");
function validTabId(id){return Number.isInteger(id)&&id>0;}
async function inject(tabId,fn){if(!validTabId(tabId))throw Error("Aba inválida.");const r=await chrome.scripting.executeScript({target:{tabId},func:fn});return r?.[0]?.result??null;}
function analyzePage(){const c=v=>String(v||"").trim().replace(/\s+/g," "),links=[...document.querySelectorAll("a[href]")],imgs=[...document.images],heads=[...document.querySelectorAll("h1,h2,h3,h4,h5,h6")],meta=[...document.querySelectorAll("meta")].map(m=>({name:m.name||null,property:m.getAttribute("property"),content:c(m.content)})).filter(x=>x.name||x.property),forms=[...document.forms].map(f=>({action:f.action||null,method:f.method||"get",controls:f.elements.length})),internal=links.filter(a=>{try{return new URL(a.href).origin===location.origin;}catch{return false;}}),altMissing=imgs.filter(i=>!c(i.alt)).length,nav=performance.getEntriesByType?.("navigation")?.[0];return{schemaVersion:1,url:location.href,title:document.title,lang:document.documentElement.lang||null,canonical:document.querySelector('link[rel="canonical"]')?.href||null,headings:heads.map(h=>({level:Number(h.tagName.slice(1)),text:c(h.textContent)})).slice(0,200),counts:{links:links.length,internalLinks:internal.length,externalLinks:links.length-internal.length,images:imgs.length,imagesWithoutAlt:altMissing,forms:forms.length,scripts:document.scripts.length,stylesheets:document.styleSheets.length,h1:document.querySelectorAll("h1").length,meta:meta.length,structuredData:document.querySelectorAll('script[type="application/ld+json"]').length},meta:meta.slice(0,100),forms,viewport:{width:innerWidth,height:innerHeight,devicePixelRatio:devicePixelRatio},performance:nav?{domContentLoaded:nav.domContentLoadedEventEnd,load:nav.loadEventEnd,transferSize:nav.transferSize}:null,generatedAt:new Date().toISOString()};}
function captureContext(){const c=v=>String(v||"").trim().replace(/\s+/g," ");return{schemaVersion:1,page:{url:location.href,title:document.title,lang:document.documentElement.lang||null},selection:c(getSelection()?.toString()).slice(0,2000),viewport:{width:innerWidth,height:innerHeight,scrollX,scrollY},focusedElement:document.activeElement?{tag:document.activeElement.tagName,id:document.activeElement.id||null,name:document.activeElement.getAttribute?.("name")||null}:null,counts:{elements:document.querySelectorAll("*").length,links:document.links.length,images:document.images.length,forms:document.forms.length},generatedAt:new Date().toISOString()};}
function advancedInspectInPage(){
  const c=v=>String(v||"").trim().replace(/\s+/g," ").slice(0,1500);
  const el=document.elementFromPoint(innerWidth/2,innerHeight/2);
  const target=el||document.activeElement;
  if(!target)return null;
  const r=target.getBoundingClientRect(),s=getComputedStyle(target);
  const aria={role:target.getAttribute("role"),label:target.getAttribute("aria-label"),labelledby:target.getAttribute("aria-labelledby"),describedby:target.getAttribute("aria-describedby"),hidden:target.getAttribute("aria-hidden")};
  const ancestors=[];let n=target;for(let i=0;n&&i<8;i++,n=n.parentElement)ancestors.push(n.tagName.toLowerCase()+ (n.id?"#"+n.id:"")+(n.classList?.length?"."+[...n.classList].slice(0,3).join("."):""));
  return{schemaVersion:2,method:"viewport-center-fallback",tag:target.tagName.toLowerCase(),id:target.id||null,classes:[...target.classList].slice(0,50),text:c(target.innerText||target.textContent),outerHTML:c(target.outerHTML).slice(0,5000),attributes:[...target.attributes].reduce((o,a)=>(o[a.name]=c(a.value).slice(0,500),o),{}),aria,rect:{x:r.x,y:r.y,width:r.width,height:r.height},styles:{display:s.display,position:s.position,color:s.color,backgroundColor:s.backgroundColor,fontSize:s.fontSize,fontWeight:s.fontWeight,zIndex:s.zIndex},ancestors,url:location.href,generatedAt:new Date().toISOString()};
}
function inspectElement(){return new Promise(resolve=>{const old=globalThis.__sifistkInspectorHandler;if(old)document.removeEventListener("click",old,true);const handler=e=>{e.preventDefault();e.stopPropagation();const el=e.target,c=v=>String(v||"").trim().replace(/\s+/g," ").slice(0,1000),attrs={};for(const a of [...el.attributes].slice(0,50))attrs[a.name]=c(a.value).slice(0,500);const r=el.getBoundingClientRect(),s=getComputedStyle(el),out={schemaVersion:1,tag:el.tagName.toLowerCase(),id:el.id||null,classes:[...el.classList].slice(0,50),text:c(el.innerText||el.textContent),attributes:attrs,rect:{x:r.x,y:r.y,width:r.width,height:r.height},styles:{display:s.display,position:s.position,color:s.color,backgroundColor:s.backgroundColor,fontSize:s.fontSize,fontWeight:s.fontWeight},url:location.href,generatedAt:new Date().toISOString()};document.removeEventListener("click",handler,true);globalThis.__sifistkInspectorHandler=null;resolve(out);};globalThis.__sifistkInspectorHandler=handler;document.addEventListener("click",handler,true);setTimeout(()=>{document.removeEventListener("click",handler,true);globalThis.__sifistkInspectorHandler=null;resolve(null);},30000);});}
async function tabsData(){if(!await chrome.permissions.contains({permissions:["tabs"]}))throw Error("A permissão de abas ainda não foi concedida.");return(await chrome.tabs.query({})).map(t=>({id:t.id,windowId:t.windowId,active:!!t.active,pinned:!!t.pinned,audible:!!t.audible,status:t.status,title:t.title||"",url:t.url||""}));}
async function permissions(){const r={};for(const p of ["tabs","downloads","sessions","notifications","tabGroups"])r[p]=await chrome.permissions.contains({permissions:[p]});return r;}
chrome.runtime.onInstalled.addListener(async()=>{await SIFISTK.ensureDefaults();try{await chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:false});}catch{}});
chrome.runtime.onStartup.addListener(()=>SIFISTK.ensureDefaults());
chrome.alarms.onAlarm.addListener(async a=>{if(a.name==="sifistk-sync"){const s=await SIFISTK.getState();if(s.settings.autoSync)try{const p=await SIFISTK.syncServer();if(p.updateAvailable&&s.settings.notifications&&await chrome.permissions.contains({permissions:["notifications"]})){await chrome.notifications.create("sifistk-update-"+Date.now(),{type:"basic",iconUrl:"icon.svg",title:"Sifistk: atualização",message:"Há uma nova versão disponível."});}}catch{}}});
chrome.commands.onCommand.addListener(async cmd=>{try{const t=(await chrome.tabs.query({active:true,currentWindow:true}))[0];if(cmd==="open-sifistk"&&t?.id)await chrome.sidePanel.open({tabId:t.id});if(cmd==="analyze-page"&&t?.id){const r=await inject(t.id,analyzePage);await chrome.storage.local.set({lastPageAnalysis:r});await SIFISTK.recordAction("page-analysis",{url:r?.url||""});}if(cmd==="capture-context"&&t?.id){const r=await inject(t.id,captureContext);await chrome.storage.local.set({lastContext:r});await SIFISTK.recordAction("context-capture",{url:r?.page?.url||""});}}catch(e){await SIFISTK.recordAction("command-error",{message:e.message});}});
chrome.runtime.onMessage.addListener((m,s,send)=>{(async()=>{await SIFISTK.ensureDefaults();switch(m?.type){case"GET_STATE":return SIFISTK.getState();case"LOGIN":return SIFISTK.login(m.email,m.password);case"LOGOUT":await SIFISTK.logout();return{ok:true};case"SYNC":return SIFISTK.syncServer();case"DIAGNOSTICS":return SIFISTK.collectDiagnostics();case"SAVE_SETTINGS":return{settings:await SIFISTK.saveSettings(m.settings)};case"ANALYZE_PAGE":{const r=await inject(m.tabId,analyzePage);await chrome.storage.local.set({lastPageAnalysis:r});await SIFISTK.recordAction("page-analysis",{url:r?.url||""});return r;}case"CAPTURE_CONTEXT":{const r=await inject(m.tabId,captureContext);await chrome.storage.local.set({lastContext:r});await SIFISTK.recordAction("context-capture",{url:r?.page?.url||""});return r;}case"INSPECT_ELEMENT":{const r=await inject(m.tabId,inspectElement);if(r)await chrome.storage.local.set({lastInspection:r});await SIFISTK.recordAction("element-inspection",{found:!!r});return r;}
case"ADVANCED_AUDIT":{const r=await inject(m.tabId,ADVANCED.auditPage);await chrome.storage.local.set({lastAdvancedAudit:r});await SIFISTK.recordAction("advanced-audit",{issues:r?.summary?.issues||0,critical:r?.summary?.critical||0});if((await SIFISTK.getState()).authToken){try{await SIFISTK.api("/api/extension/report",{method:"POST",body:JSON.stringify({report:{type:"advanced-audit",data:r}})});}catch{}}return r;}
case"COMPATIBILITY":{const r=await ADVANCED.compatibility();await chrome.storage.local.set({compatibilityReport:r});await SIFISTK.recordAction("compatibility-check",{missing:r.missing?.length||0});return r;}
case"ADVANCED_INSPECT":{const r=await inject(m.tabId,advancedInspectInPage);if(r)await chrome.storage.local.set({lastAdvancedInspection:r});await SIFISTK.recordAction("advanced-element-inspection",{found:!!r});return r;}case"LIST_TABS":return tabsData();case"CLOSE_TAB":if(!await chrome.permissions.contains({permissions:["tabs"]}))throw Error("Permissão de abas não concedida.");await chrome.tabs.remove(Number(m.tabId));await SIFISTK.recordAction("tab-close",{tabId:Number(m.tabId)});return{ok:true};case"LIST_SESSIONS":if(!await chrome.permissions.contains({permissions:["sessions"]}))throw Error("Permissão de sessões não concedida.");return chrome.sessions.getRecentlyClosed({maxResults:10});case"RESTORE_SESSION":if(!await chrome.permissions.contains({permissions:["sessions"]}))throw Error("Permissão de sessões não concedida.");return chrome.sessions.restore(m.sessionId);case"REQUEST_PERMISSIONS":return{granted:await SIFISTK.requestPermissions(m.permissions||[])};
case"SEARCH":return SIFISTK.search(m.query);
case"SAVE_WORK_SESSION":{if(!await chrome.permissions.contains({permissions:["tabs"]}))throw Error("Permissão de abas não concedida.");return SIFISTK.saveWorkSession(m.name,await chrome.tabs.query({}));}
case"GET_WORK_SESSIONS":return (await SIFISTK.getState()).workSessions||[];
case"RESTORE_WORK_SESSION":return SIFISTK.restoreWorkSession(m.session);
case"DOWNLOAD_EXTENSION":{const s=await SIFISTK.getState(),v=await SIFISTK.api("/api/extension/version");if(!v.downloadUrl)throw Error("O servidor ainda não publicou um pacote oficial para download.");if(!await chrome.permissions.contains({permissions:["downloads"]}))throw Error("Conceda a permissão de downloads nas configurações.");const id=await chrome.downloads.download({url:v.downloadUrl,filename:"sifistk-"+(v.latestVersion||SIFISTK.VERSION)+".zip",saveAs:true});await SIFISTK.recordAction("extension-download",{id});return{id};}case"PERMISSIONS":return permissions();
case"NOTIFY":{if(!await chrome.permissions.contains({permissions:["notifications"]}))throw Error("Permissão de notificações não concedida.");await chrome.notifications.create("sifistk-"+Date.now(),{type:"basic",iconUrl:"icon.svg",title:"Sifistk",message:String(m.message||"Atualização disponível.")});return{ok:true};}case"DOWNLOAD_REPORT":{const r=m.report||await SIFISTK.collectDiagnostics(),id=await SIFISTK.downloadJson(m.filename||"sifistk-diagnostic.json",r);await SIFISTK.recordAction("report-download",{id});return{id};}case"CLEAR_DATA":await SIFISTK.clearLocalData();return{ok:true};case"OPEN_OPTIONS":await chrome.runtime.openOptionsPage();return{ok:true};case"OPEN_SIDE_PANEL":{const tabId=s.tab?.id||(await chrome.tabs.query({active:true,currentWindow:true}))[0]?.id;if(!tabId)throw Error("Não foi possível identificar a aba atual.");await chrome.sidePanel.open({tabId});return{ok:true};}default:throw Error("Comando desconhecido.");}})().then(r=>send({ok:true,result:r})).catch(e=>send({ok:false,error:e.message}));return true;});
(async()=>{await SIFISTK.ensureDefaults();await chrome.alarms.create("sifistk-sync",{delayInMinutes:1,periodInMinutes:360});try{await SIFISTK.syncServer();}catch{}})();